Repository milieuinfo/webcomponent-vl-ui-map, pull requests merged in 2019-10, with the labels that each got.

#60 Roll back dependency vl-ui-select to ^1.1.11
  package.json
Labels: dependencies

#61 Update dependency sass to v1.23.0
  package.json
Labels: dependencies

#62 Update dependency rollup to v1.23.1
  package.json
Labels: dependencies

#68 #67 pad replace fix in build
  package.json
Labels: bug

#74 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package.json
Labels: maintenance

#76 Update dependency rollup to v1.24.0
  package.json
Labels: dependencies

#77 Update dependency rollup to v1.25.1
  package.json
Labels: dependencies

#84 Update README.md
  README.md
Labels: maintenance

#85 Update README.md
  README.md
  package.json
Labels: maintenance
