Repository milieuinfo/webcomponent-vl-ui-map, pull requests merged in 2019-09, with the labels that each got.

#36 UIG-218
  src/vl-map.js
Labels: maintenance

#37 UIG-218
  src/vl-map-action.js
  src/vl-map-baselayer-grb-gray.js
  src/vl-map-baselayer-grb-ortho.js
  src/vl-map-baselayer-grb.js
  src/vl-map-baselayer.js
  src/vl-map-layer-circle-style.js
  src/vl-map-layer-style.js
  src/vl-map-layer.js
  src/vl-map-search.js
  src/vl-map-select-action.js
Labels: maintenance

#38 UIG-218
  src/vl-map-action.js
  src/vl-map-baselayer-grb-gray.js
  src/vl-map-baselayer-grb-ortho.js
  src/vl-map-baselayer-grb.js
  src/vl-map-baselayer.js
  src/vl-map-layer-circle-style.js
  src/vl-map-layer-style.js
  src/vl-map-layer.js
  src/vl-map-search.js
  src/vl-map-select-action.js
  src/vl-map.js
Labels: maintenance

#39 Automatic commit via update script
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package.json
Labels: maintenance

#29 Update dependency rollup-plugin-terser to v5
  package.json
Labels: renovate

#23 Update dependency rollup to v1.19.4
  package.json
Labels: renovate

#24 Update dependency sass to v1.22.9
  package.json
Labels: renovate

#22 Update dependency replace to v1.1.0
  package.json
Labels: renovate

#21 Update dependency np to v3.1.0
  package.json
Labels: renovate

#20 Update dependency concurrently to v4.1.1
  package.json
Labels: renovate

#46 Update dependency vl-ui-select to v1.1.10
  package.json
Labels: dependencies

#45 Update dependency vl-ui-icon to v2.0.11
  package.json
Labels: dependencies

#44 Update dependency vl-ui-core to v1.4.6
  package.json
Labels: dependencies

#43 Update dependency sass to v1.22.10
  package.json
Labels: dependencies

#42 Update dependency rollup to v1.21.2
  package.json
Labels: dependencies

#41 Update dependency replace to v1.1.1
  package.json
Labels: dependencies

#40 Update dependency concurrently to v4.1.2
  package.json
Labels: dependencies

#47 Update dependency vl-ui-core to v1.4.7
  package.json
Labels: dependencies

#52 Update dependency vl-ui-select to v1.1.11
  package.json
Labels: dependencies

#51 Update dependency vl-ui-icon to v2.0.12
  package.json
Labels: dependencies

#49 Update dependency rollup-plugin-terser to v5.1.2
  package.json
Labels: dependencies

#50 Update dependency sass to v1.22.12
  package.json
Labels: dependencies

#48 Update dependency rollup to v1.21.4
  package.json
Labels: dependencies

#53 Automatic commit via update script
  package.json
Labels: maintenance

#54 Update and install latest util
  .github/ISSUE_TEMPLATE/task.md
  bamboo-specs/bamboo.yml
  package.json
Labels: maintenance

#56 Update dependency rollup to v1.22.0
  package.json
Labels: dependencies
