Repository milieuinfo/webcomponent-vl-ui-map, pull requests merged in 2020-02, with the labels that each got.

#118 Update vl-ui-select versie
  package.json
Labels: chore

#121 Fix auto-extend, maak VlMapLayer#zoomToExtend publiek en introduceer auto-extend-max-zoom
  demo/vl-map-layer.html
  package-lock.json
  rollup.config.js
  src/vl-map-layer.js
  src/vl-map.js
  test/unit/vl-map-layer.test.html
  test/unit/vl-map.test.html
Labels: bug, enhancement

#125 Stijl import vervangen door inhoud, probleem met absolute paden
  package-lock.json
  package.json
  src/vl-map.js
Labels: bug

#126 Nieuwe structuur en build scripts implementatie vervangen door vl-ui-util build implementatie
  CODEOWNERS
  bamboo-specs/bamboo.yml
  demo/vl-map-circle-style.html
  demo/vl-map-layer.html
  demo/vl-map-overview-map.html
  demo/vl-map-search.html
  demo/vl-map-select-action.html
  demo/vl-map.html
  docker-compose-release.yml
  package-lock.json
  package.json
  src/index.js
  src/style.css
  src/style.css.map
  src/vl-map-action.js
  src/vl-map-all.js
  src/vl-map-baselayer.js
  src/vl-map-layer-style.js
  src/vl-map-layer.js
  src/vl-map-overview-map.js
  src/vl-map-search.js
  src/vl-map.js
  style.css.map
  test/docker-compose.yml
  test/e2e/map.test.js
  test/unit/vl-map-baselayer-grb-gray.test.html
  test/unit/vl-map-baselayer-grb-ortho.test.html
  test/unit/vl-map-baselayer-grb.test.html
  test/unit/vl-map-baselayer.test.html
  test/unit/vl-map-layer-circle-style.test.html
  test/unit/vl-map-layer-style.test.html
  test/unit/vl-map-layer.test.html
  test/unit/vl-map-overview-map.test.html
  test/unit/vl-map-search.html
  test/unit/vl-map-select-action.test.html
  test/unit/vl-map.test.html
  vl-map.js
  vl-map.min.js
  vl-map.src.js
Labels: chore
