Repository milieuinfo/webcomponent-vl-ui-map, pull requests merged in 2020-01, with the labels that each got.

#109 Update vl-ui-util
  bamboo-specs/bamboo.yml
  demo/demo.js
  package.json
  test/docker-compose.yml
Labels: maintenance

#110 Nieuwe opzet E2E testen
  .mocharc.js
  index.js
  package.json
  test/e2e/components/vl-map.js
  test/e2e/map.test.js
  test/e2e/pages/vl-map.page.js
  test/unit/docker-compose.yml
  test/unit/dummy-vl-map-layer.js
  test/unit/ol-util.js
  test/unit/vl-map-baselayer-grb-gray.test.html
  test/unit/vl-map-baselayer-grb-ortho.test.html
  test/unit/vl-map-baselayer-grb.test.html
  test/unit/vl-map-baselayer.test.html
  test/unit/vl-map-layer-circle-style.test.html
  test/unit/vl-map-layer-style.test.html
  test/unit/vl-map-layer.test.html
  test/unit/vl-map-overview-map.test.html
  test/unit/vl-map-search.html
  test/unit/vl-map-select-action.test.html
  test/unit/vl-map.test.html
  test/wct.docker.conf.json
Labels: bugfix

#112 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnen
  package.json
Labels: chore

#111 Update vl-ui-util
  package.json
  test/docker-compose.yml
Labels: maintenance

#113 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package.json
  test/docker-compose.yml
Labels: maintenance

#114 Update vl-ui-util
  bamboo-specs/bamboo.yml
  docker-compose-release.yml
  package.json
Labels: maintenance
