Repository milieuinfo/webcomponent-vl-ui-map, pull requests merged in 2021-04, with the labels that each got.

#249 Update vl-ui-util dependency met oplossing voor centrale wijziging font pad
  package-lock.json
  package.json
  src/style.css
Labels: chore

#247 De cirkel stijl variant hield geen rekening met de `appliesTo` logica waardoor deze altijd toegepast werd
  dist/vl-map-layer-circle-style.js
  dist/vl-map-layer-circle-style.min.js
  dist/vl-map-layer-circle-style.src.js
  dist/vl-map-layer-style.js
  dist/vl-map-layer-style.min.js
  dist/vl-map-layer-style.src.js
  src/vl-map-layer-circle-style.js
  src/vl-map-layer-style.js
  test/unit/vl-map-layer-circle-style.test.html
  test/unit/vl-map-layer-style.test.html
Labels: bug

#248 Publieke methode om `boundingBox` van kaartlaag op te vragen
  src/vl-map-features-layer.js
  test/unit/vl-map-features-layer.test.html
Labels: chore

#244 Snapping bij tekenen van punten
  demo/vl-map-draw-actions.html
  dist/vl-map-delete-action.js
  dist/vl-map-delete-action.min.js
  dist/vl-map-delete-action.src.js
  dist/vl-map-draw-action.js
  dist/vl-map-draw-action.min.js
  dist/vl-map-draw-action.src.js
  dist/vl-map-draw-line-action.js
  dist/vl-map-draw-line-action.min.js
  dist/vl-map-draw-line-action.src.js
  dist/vl-map-draw-point-action.js
  dist/vl-map-draw-point-action.min.js
  dist/vl-map-draw-point-action.src.js
  dist/vl-map-draw-polygon-action.js
  dist/vl-map-draw-polygon-action.min.js
  dist/vl-map-draw-polygon-action.src.js
  dist/vl-map-layer-style.js
  dist/vl-map-layer-style.min.js
  dist/vl-map-layer-style.src.js
  dist/vl-map-select-action.js
  dist/vl-map-select-action.min.js
  dist/vl-map-select-action.src.js
  dist/vl-map-vector-layer.js
  dist/vl-map-vector-layer.min.js
  dist/vl-map-vector-layer.src.js
  dist/vl-map.js
  dist/vl-map.min.js
  dist/vl-map.src.js
  package-lock.json
  package.json
  src/vl-map-delete-action.js
  src/vl-map-draw-action.js
  src/vl-map-draw-line-action.js
  src/vl-map-draw-point-action.js
  src/vl-map-draw-polygon-action.js
  src/vl-map-layer-style.js
  src/vl-map-select-action.js
  src/vl-map-vector-layer.js
  src/vl-map.js
  test/e2e/components/vl-map-draw-point-action.js
  test/e2e/components/vl-map-features-layer.js
  test/e2e/map-draw-actions.test.js
  test/e2e/pages/vl-map-draw-actions.page.js
  test/e2e/pages/vl-map-wfs-layer.page.js
  test/unit/vl-map-delete-action.test.html
  test/unit/vl-map-draw-line-action.test.html
  test/unit/vl-map-draw-point-action.test.html
  test/unit/vl-map-draw-polygon-action.test.html
  test/unit/vl-map-layer-circle-style.test.html
  test/unit/vl-map-layer-style.test.html
  test/unit/vl-map-layer-switcher.test.html
  test/unit/vl-map-select-action.test.html
  test/unit/vl-map-vector-layer.test.html
Labels: enhancement

#250 Interactie met de kaart e2e componenten gewijzigd van pixels naar Lambertcoördinaten (1972)
  src/vl-map-vector-layer.js
  test/e2e/components/vl-map-draw-line-action.js
  test/e2e/components/vl-map-draw-point-action.js
  test/e2e/components/vl-map-draw-polygon-action.js
  test/e2e/components/vl-map.js
  test/e2e/map-draw-actions.test.js
Labels: breaking change, chore
