Repository milieuinfo/webcomponent-vl-ui-map, pull requests merged in 2021-03, with the labels that each got.

#234 Introductie vl-select-location component
  demo/vl-map-search.html
  dist/vl-map-all.js
  dist/vl-map-all.min.js
  dist/vl-map-all.src.js
  dist/vl-map-search.js
  dist/vl-map-search.min.js
  dist/vl-map-search.src.js
  dist/vl-select-location.js
  dist/vl-select-location.min.js
  dist/vl-select-location.src.js
  src/vl-map-all.js
  src/vl-map-search.js
  src/vl-select-location.js
  test/e2e/components/vl-map-search.js
  test/e2e/map-search.test.js
  test/unit/vl-map-search.test.html
  test/unit/vl-select-location.test.html
Labels: breaking change, enhancement

#235 Dependency proj4.js wordt geïmporteerd via ES module
  package-lock.json
  package.json
  src/vl-map-action.js
  src/vl-map-all.js
  src/vl-map-baselayer-grb-gray.js
  src/vl-map-baselayer-grb-ortho.js
  src/vl-map-baselayer-grb.js
  src/vl-map-baselayer.js
  src/vl-map-delete-action.js
  src/vl-map-draw-line-action.js
  src/vl-map-draw-point-action.js
  src/vl-map-draw-polygon-action.js
  src/vl-map-features-layer.js
  src/vl-map-image-wms-layer.js
  src/vl-map-layer-action.js
  src/vl-map-layer-circle-style.js
  src/vl-map-layer-style.js
  src/vl-map-layer-switcher.js
  src/vl-map-modify-action.js
  src/vl-map-overview-map.js
  src/vl-map-search.js
  src/vl-map-select-action.js
  src/vl-map-side-sheet-menu-item.js
  src/vl-map-side-sheet-menu.js
  src/vl-map-side-sheet.js
  src/vl-map-tiled-wms-layer.js
  src/vl-map-wfs-layer.js
  src/vl-map-wmts-layer.js
  src/vl-map.js
  test/unit/vl-map.test.html
Labels: chore

#238 Export test componenten voor voortoets
  index.js
Labels: enhancement

#241 Documentatie links verbeteringen en aanvullingen
  src/vl-map-action.js
  src/vl-map-layer-action.js
  src/vl-map-layer-switcher.js
  src/vl-map-layer.js
  src/vl-map-side-sheet.js
  src/vl-map-vector-layer.js
  src/vl-map.js
Labels: chore
