Repository milieuinfo/webcomponent-vl-ui-map, pull requests merged in 2021-02, with the labels that each got.

#205 CommonJS imports vervangen door ES varianten
  package-lock.json
  package.json
  src/index.js
Labels: chore

#208 Update vl-ui-core dependency
  package-lock.json
  package.json
Labels: chore

#213 Update dependencies
  package-lock.json
  package.json
Labels: chore

#217 Placeholder zoeken op adres uitgebreid met vermelding coördinaat en compacter gemaakt
  src/vl-map-search.js
  test/unit/vl-map-search.test.html
Labels: bug

#221 Fix features ophalen van laag
  demo/vl-map-layer-style.html
  src/vl-map-layer.js
  test/e2e/components/vl-map-action.js
  test/e2e/components/vl-map-draw-line-action.js
  test/e2e/components/vl-map-draw-point-action.js
  test/e2e/components/vl-map-draw-polygon-action.js
  test/e2e/components/vl-map-layer.js
  test/e2e/components/vl-map.js
  test/e2e/map-circle-style.test.js
  test/e2e/map-layer-style.test.js
  test/e2e/map-layer-switcher.test.js
  test/e2e/map-search.test.js
  test/e2e/pages/vl-map-circle-style.page.js
  test/e2e/pages/vl-map-draw-actions.page.js
  test/e2e/pages/vl-map-layer-style.page.js
  test/e2e/pages/vl-map-layer-switcher.page.js
  test/e2e/pages/vl-map-layer.page.js
  test/e2e/pages/vl-map-overview-map.page.js
  test/e2e/pages/vl-map-search.page.js
  test/e2e/pages/vl-map-select-action.page.js
  test/e2e/pages/vl-map-side-sheet-menu-item.page.js
  test/e2e/pages/vl-map-side-sheet-menu.page.js
  test/e2e/pages/vl-map.page.js
Labels: bug

#218 Introduceer WMS, WMTS & WFS overlays (#203)
  demo/vl-map-circle-style.html
  demo/vl-map-draw-actions.html
  demo/vl-map-features-layer.html
  demo/vl-map-layer-switcher.html
  demo/vl-map-select-action.html
  demo/vl-map-wfs-layer.html
  demo/vl-map-wms-layer.html
  demo/vl-map-wmts-layer.html
  package-lock.json
  package.json
  src/style.css
  src/style.css.map
  src/vl-map-all.js
  src/vl-map-features-layer.js
  src/vl-map-image-wms-layer.js
  src/vl-map-layer-action.js
  src/vl-map-layer-switcher.js
  src/vl-map-layer.js
  src/vl-map-tiled-wms-layer.js
  src/vl-map-vector-layer.js
  src/vl-map-wfs-layer.js
  src/vl-map-wms-layer.js
  src/vl-map-wmts-layer.js
  src/vl-map.js
  test/e2e/components/vl-map-draw-point-action.js
  test/e2e/components/vl-map-features-layer.js
  test/e2e/components/vl-map-image-wms-layer.js
  test/e2e/components/vl-map-layer.js
  test/e2e/components/vl-map-tiled-wms-layer.js
  test/e2e/components/vl-map-wfs-layer.js
  test/e2e/components/vl-map-wms-layer.js
  test/e2e/components/vl-map-wmts-layer.js
  test/e2e/components/vl-map.js
  test/e2e/map-draw-actions.test.js
  test/e2e/map-features-layer.test.js
  test/e2e/map-wfs-layer.test.js
  test/e2e/map-wms-layer.test.js
  test/e2e/map-wmts-layer.test.js
  test/e2e/pages/vl-map-features-layer.page.js
  test/e2e/pages/vl-map-select-action.page.js
  test/e2e/pages/vl-map-wfs-layer.page.js
  test/e2e/pages/vl-map-wms-layer.page.js
  test/e2e/pages/vl-map-wmts-layer.page.js
  test/unit/lambert-coordinaat.test.html
  test/unit/vl-map-features-layer.test.html
  test/unit/vl-map-image-wms-layer.test.html
  test/unit/vl-map-layer-action.test.html
  test/unit/vl-map-layer-circle-style.test.html
  test/unit/vl-map-layer-style.test.html
  test/unit/vl-map-layer-switcher.test.html
  test/unit/vl-map-layer.test.html
  test/unit/vl-map-select-action.test.html
  test/unit/vl-map-tiled-wms-layer.test.html
  test/unit/vl-map-vector-layer.test.html
  test/unit/vl-map-wfs-layer.test.html
  test/unit/vl-map-wmts-layer.test.html
Labels: breaking change, enhancement

#219 Introductie interactie om punt, lijn en polygoon te kunnen verwijderen
  demo/vl-map-delete-action.html
  package-lock.json
  package.json
  src/style.css
  src/style.css.map
  src/vl-map-all.js
  src/vl-map-delete-action.js
  test/e2e/components/vl-map-delete-action.js
  test/e2e/components/vl-map-features-layer.js
  test/e2e/components/vl-map-layers.js
  test/e2e/components/vl-map.js
  test/e2e/map-delete-action.test.js
  test/e2e/pages/vl-map-delete-action.page.js
  test/e2e/pages/vl-map-select-action.page.js
  test/unit/vl-map-delete-action.test.html
Labels: enhancement

#226 Update vl-ui-util dependency
  dist/style.css
  dist/style.css.map
  dist/vl-map-all.src.js
  dist/vl-map-search.js
  dist/vl-map-search.min.js
  dist/vl-map-search.src.js
  dist/vl-map.min.js
  dist/vl-map.src.js
  package-lock.json
  package.json
Labels: chore

#224 UItbreiding e2e test voor aan- en uitvinken van kaartlagen
  demo/vl-map-layer-switcher.html
  demo/vl-map-wfs-layer.html
  demo/vl-map-wmts-layer.html
  src/vl-map-layer-switcher.js
  test/e2e/components/vl-map-layer-switcher.js
  test/e2e/map-layer-switcher.test.js
Labels: chore

#220 Introductie kaart interactie om feature te kunnen wijzigen
  demo/vl-map-modify-actions.html
  package-lock.json
  src/vl-map-all.js
  src/vl-map-modify-action.js
  test/e2e/components/vl-map-action.js
  test/e2e/components/vl-map-features-layer.js
  test/e2e/components/vl-map-modify-action.js
  test/e2e/components/vl-map.js
  test/e2e/map-modify-actions.test.js
  test/e2e/map-search.test.js
  test/e2e/pages/vl-map-modify-actions.page.js
Labels: enhancement

#233 Update vl-mapactions dependency
  package-lock.json
  package.json
Labels: chore
